# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: trailing-whitespace
      exclude: (\.md|\.csv)$
    - id: end-of-file-fixer
      exclude: (\.md|setup.cfg)$
    - id: check-ast
    - id: check-yaml
    - id: check-added-large-files
      args: [ '--maxkb=200' ]
    - id: check-merge-conflict
    - id: detect-private-key
    - id: mixed-line-ending
      args: [ '--fix=lf' ]
      exclude: (\.bat)$


- repo: https://github.com/PyCQA/isort.git
  rev: 5.7.0
  hooks:
    - id: isort


- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.6
  hooks:
    - id: autopep8


- repo: local
  hooks:
    - id: unittest
      name: Run all unit tests crispy cookie
      language: system
      entry: python -m unittest discover -s tests
      types: [ python ]
      pass_filenames: false
